yaParams = {}

((d, w, c) ->
  (w[c] = w[c] or []).push ->
    try
      w.yaCounter29097965 = new (Ya.Metrika)(
        id: 29097965
        webvisor: true
        clickmap: true
        trackLinks: true
        accurateTrackBounce: true
        trackHash: true
        params: window.yaParams or {})
    catch e
    return
  n = d.getElementsByTagName('script')[0]
  s = d.createElement('script')

  f = ->
    n.parentNode.insertBefore s, n
    return

  s.type = 'text/javascript'
  s.async = true
  s.src = (if d.location.protocol == 'https:' then 'https:' else 'http:') + '//mc.yandex.ru/metrika/watch.js'
  if w.opera == '[object Opera]'
    d.addEventListener 'DOMContentLoaded', f, false
  else
    f()
  return
) document, window, 'yandex_metrika_callbacks'

# ---
# generated by js2coffee 2.0.1
